### ISSUE TITLE
schedule setup bug

### ISSUE THREAD

**Issue by LeGmask** [schoolsyst/frontend#49]
**Describe the bug**
When you use a pair week or impair week it bug the date of the courses

**Screenshots**
![image](https://user-images.githubusercontent.com/53308142/76441239-61dd0700-63bf-11ea-8d46-6cc059834f7f.png)
![image](https://user-images.githubusercontent.com/53308142/76441252-67d2e800-63bf-11ea-8dfe-d4052f72fe86.png)

**Comment by LeGmask** [comment]
doing weird thing 
![image](https://user-images.githubusercontent.com/53308142/76441758-3ad30500-63c0-11ea-9ab7-53aeb9988de1.png)

**Comment by LeGmask** [comment]
![image](https://user-images.githubusercontent.com/53308142/76442840-cb5e1500-63c1-11ea-890d-b222275b40ac.png)

**Comment by LeGmask** [comment]
And i can't complete the setup it doing schedule at the infinity

**Comment by LeGmask** [comment]
![image](https://user-images.githubusercontent.com/53308142/76443094-31e33300-63c2-11ea-9eb1-14db2fd139c5.png)
Plus tard button doing nothing, but close window alert

**Comment by ewen-lbh** [comment]
Thanks, this bug is unfortunately very known and pretty much cripples the whole setup experience.
I plan on rewriting (for the third time) the schedule rendering engine from scratch (as this is a very peculiar need that no one seems to be interested making a library for).

I also plan on making the setup less in-your-face, by letting the user wander around the interface and tell them "click this to add your schedule".

But don't worry, your schedule are saved at the right time, and the timeline will be correctly displayed, as well as all other features relying on your schedule. It's only the schedule display engine that's broken af.

**Comment by ewen-lbh** [comment]
@LeGmask this issue is being resolved actively, see the linked PR I just made 😄

**Comment by LeGmask** [comment]
@ewen-lbh Hope this time it will work, I'm here to broke thing 😅
